service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-1
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:*
      Resource: 
       - arn:aws:dynamodb:us-west-1:421756196726:table/TodoTable

functions:
  hello:
    handler: src/hello.handler
    events:
      - httpApi: 
          path: /
          method: get
  addTodo:
    handler: src/addTodo.handler
    events:
      - httpApi: 
          path: /todo
          method: post
  fetchTodos:
    handler: src/fetchTodos.handler
    events:
      - httpApi: 
          path: /todos
          method: get
  fetchTodo:
    handler: src/fetchTodo.handler
    events:
      - httpApi: 
          path: /todo/{id}
          method: get
  updateTodo:
    handler: src/updateTodo.handler
    events:
      - httpApi: 
          path: /todo/{id}
          method: put

resources:
  Resources:
    TodoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TodoTable
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
